# arxivの学問領域の指定
subject: 'cat:q-bio.BM OR cat:q-bio.CB OR cat:q-bio.GN OR cat:physics.bio-ph'

# 検索キーワード
keywords:
        virus: 5
        enhancer: 4
        chromatin: 3
        CRISPR: 3
        cell: 2

# 通知の閾値
score_threshold: 0
